enableWelcomeMessage: false
enableCampaigns: false 
enableChatTargeting: false 
welcomeMessageDelay: 5000 

backgroundColor: '#ffffff'
textColorOnBackground: '#666666'

foregroundColor: '#0176ff'
textColorOnForeground: '#ffffff'