# TEMPORARY UNUSED SETTINGS
enableWelcomeMessage: false
enableCampaigns: false 
enableChatTargeting: false 
welcomeMessageDelay: 5000 

# DEFAULT SETTINGS
botName: 'Default Bot' ## Default name of your bot
botAvatarUrl: 'https://avatars3.githubusercontent.com/u/1315508?v=4&s=400' ## Default avatar url of the image
welcomeMsg: | ## Welcome message that shows at on pop-up (multi-lines)
  Hey guys!
  Curious about our offer?
  This is the default message...

# COLOR SETTINGS
backgroundColor: '#ffffff' ## Color of the background 
textColorOnBackground: '#666666' ## Color of the text on the background
foregroundColor: '#0176ff' ## Element background color (header, composer, button..)
textColorOnForeground: '#ffffff'  ## Element text color (header, composer, button..)